# Generated by Django 5.2.17 on 2026-08-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="region",
            field=models.CharField(
                choices=[
                    ("common", "전국 공통"),
                    ("seoul", "서울"),
                    ("cheonan", "천안"),
                    ("busan_namgu", "부산 남구"),
                    ("incheon_michuhol", "인천 미추홀구"),
                    ("sejong", "세종"),
                    ("daejeon", "대전"),
                    ("ulsan", "울산"),
                    ("suwon", "수원"),
                    ("jeju", "제주"),
                ],
                default="seoul",
                max_length=50,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="region",
            field=models.CharField(
                choices=[
                    ("common", "전국 공통"),
                    ("seoul", "서울"),
                    ("cheonan", "천안"),
                    ("busan_namgu", "부산 남구"),
                    ("incheon_michuhol", "인천 미추홀구"),
                    ("sejong", "세종"),
                    ("daejeon", "대전"),
                    ("ulsan", "울산"),
                    ("suwon", "수원"),
                    ("jeju", "제주"),
                ],
                default="seoul",
                help_text="이 대화방에서 사용하는 지역. 기본값은 회원 프로필의 region 입니다.",
                max_length=50,
                verbose_name="지역",
            ),
        ),
    ]
