# Generated by Django 5.2.17 on 2026-08-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("common", "전국 공통"),
                    ("seoul", "서울"),
                    ("cheonan", "천안"),
                    ("busan_namgu", "부산 남구"),
                    ("incheon_michuhol", "인천 미추홀구"),
                    ("sejong", "세종"),
                    ("daejeon", "대전"),
                    ("ulsan", "울산"),
                    ("suwon", "수원"),
                    ("jeju", "제주"),
                ],
                db_index=True,
                help_text="비어 있거나 common 이면 전국 공통으로 취급합니다.",
                max_length=50,
                null=True,
                verbose_name="적용 지역",
            ),
        ),
    ]
